// Code generated by protoc-gen-go. DO NOT EDIT.
// source: destroyer.proto

package destroyer_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventMessage struct {
	Id                   string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Data                 []*TargetResponse `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	CreatedOn            string            `protobuf:"bytes,4,opt,name=CreatedOn,proto3" json:"CreatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EventMessage) Reset()         { *m = EventMessage{} }
func (m *EventMessage) String() string { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()    {}
func (*EventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a860e7296c45340, []int{0}
}

func (m *EventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMessage.Unmarshal(m, b)
}
func (m *EventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMessage.Marshal(b, m, deterministic)
}
func (m *EventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMessage.Merge(m, src)
}
func (m *EventMessage) XXX_Size() int {
	return xxx_messageInfo_EventMessage.Size(m)
}
func (m *EventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMessage proto.InternalMessageInfo

func (m *EventMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventMessage) GetData() []*TargetResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EventMessage) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

type TargetRequestMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetRequestMessage) Reset()         { *m = TargetRequestMessage{} }
func (m *TargetRequestMessage) String() string { return proto.CompactTextString(m) }
func (*TargetRequestMessage) ProtoMessage()    {}
func (*TargetRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a860e7296c45340, []int{1}
}

func (m *TargetRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetRequestMessage.Unmarshal(m, b)
}
func (m *TargetRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetRequestMessage.Marshal(b, m, deterministic)
}
func (m *TargetRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetRequestMessage.Merge(m, src)
}
func (m *TargetRequestMessage) XXX_Size() int {
	return xxx_messageInfo_TargetRequestMessage.Size(m)
}
func (m *TargetRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TargetRequestMessage proto.InternalMessageInfo

func (m *TargetRequestMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TargetResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	CreatedOn            string   `protobuf:"bytes,3,opt,name=CreatedOn,proto3" json:"CreatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetResponse) Reset()         { *m = TargetResponse{} }
func (m *TargetResponse) String() string { return proto.CompactTextString(m) }
func (*TargetResponse) ProtoMessage()    {}
func (*TargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a860e7296c45340, []int{2}
}

func (m *TargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetResponse.Unmarshal(m, b)
}
func (m *TargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetResponse.Marshal(b, m, deterministic)
}
func (m *TargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetResponse.Merge(m, src)
}
func (m *TargetResponse) XXX_Size() int {
	return xxx_messageInfo_TargetResponse.Size(m)
}
func (m *TargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TargetResponse proto.InternalMessageInfo

func (m *TargetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TargetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TargetResponse) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

type TargetResponseMessage struct {
	TargetResponses      []*TargetResponse `protobuf:"bytes,1,rep,name=TargetResponses,proto3" json:"TargetResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TargetResponseMessage) Reset()         { *m = TargetResponseMessage{} }
func (m *TargetResponseMessage) String() string { return proto.CompactTextString(m) }
func (*TargetResponseMessage) ProtoMessage()    {}
func (*TargetResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a860e7296c45340, []int{3}
}

func (m *TargetResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetResponseMessage.Unmarshal(m, b)
}
func (m *TargetResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetResponseMessage.Marshal(b, m, deterministic)
}
func (m *TargetResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetResponseMessage.Merge(m, src)
}
func (m *TargetResponseMessage) XXX_Size() int {
	return xxx_messageInfo_TargetResponseMessage.Size(m)
}
func (m *TargetResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TargetResponseMessage proto.InternalMessageInfo

func (m *TargetResponseMessage) GetTargetResponses() []*TargetResponse {
	if m != nil {
		return m.TargetResponses
	}
	return nil
}

func init() {
	proto.RegisterType((*EventMessage)(nil), "destroyer_pb.EventMessage")
	proto.RegisterType((*TargetRequestMessage)(nil), "destroyer_pb.TargetRequestMessage")
	proto.RegisterType((*TargetResponse)(nil), "destroyer_pb.TargetResponse")
	proto.RegisterType((*TargetResponseMessage)(nil), "destroyer_pb.TargetResponseMessage")
}

func init() {
	proto.RegisterFile("destroyer.proto", fileDescriptor_8a860e7296c45340)
}

var fileDescriptor_8a860e7296c45340 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0x87, 0x4d, 0x5b, 0x94, 0x9d, 0xcd, 0x0e, 0x82, 0x42, 0x28, 0xbb, 0x18, 0x11, 0x64, 0x57,
	0x45, 0xe6, 0x23, 0x4c, 0x85, 0x09, 0x2a, 0x14, 0x2f, 0x76, 0x37, 0xb2, 0xf5, 0x30, 0x0a, 0x36,
	0xe9, 0x92, 0x54, 0xf0, 0xd6, 0x77, 0xf2, 0xfd, 0x84, 0xb8, 0xce, 0x66, 0x6a, 0xf1, 0x2e, 0x39,
	0xe7, 0xfc, 0x3e, 0xbe, 0xfc, 0x81, 0x61, 0x8e, 0xc6, 0x6a, 0xf5, 0x86, 0x3a, 0xad, 0xb4, 0xb2,
	0x8a, 0x0e, 0xf6, 0x85, 0x65, 0xb5, 0xe2, 0xef, 0x04, 0x06, 0xb7, 0xaf, 0x28, 0xed, 0x03, 0x1a,
	0x23, 0x36, 0x48, 0x63, 0x08, 0xe6, 0x39, 0x23, 0x63, 0x32, 0xe9, 0x65, 0xc1, 0x3c, 0xa7, 0x14,
	0xa2, 0x47, 0x51, 0x22, 0x0b, 0x5c, 0xc5, 0xad, 0xe9, 0x15, 0x44, 0x37, 0xc2, 0x0a, 0x16, 0x8e,
	0xc3, 0x49, 0x7f, 0x3a, 0x4a, 0xdb, 0xc4, 0xf4, 0x59, 0xe8, 0x0d, 0xda, 0x0c, 0x4d, 0xa5, 0xa4,
	0xc1, 0xcc, 0x4d, 0xd2, 0x11, 0xf4, 0x66, 0x1a, 0x85, 0xc5, 0xfc, 0x49, 0xb2, 0xc8, 0xa1, 0xbe,
	0x0b, 0xfc, 0x12, 0xce, 0x9a, 0xd4, 0xb6, 0x46, 0xf3, 0x97, 0x0b, 0x5f, 0x40, 0xec, 0xd3, 0x7f,
	0xd8, 0x32, 0x38, 0xd9, 0x85, 0x77, 0xc2, 0xcd, 0xd6, 0x37, 0x08, 0x0f, 0x0d, 0x96, 0x70, 0xee,
	0x93, 0x9b, 0xd8, 0x1d, 0x0c, 0xfd, 0x86, 0x61, 0xe4, 0x1f, 0xa7, 0x3e, 0x0c, 0x4d, 0x3f, 0x08,
	0x9c, 0xce, 0x54, 0x59, 0xd6, 0xb2, 0x58, 0x0b, 0x5b, 0x28, 0x49, 0xef, 0x21, 0x16, 0xeb, 0x6d,
	0x5d, 0x68, 0xfc, 0x9a, 0x35, 0x34, 0xf1, 0x91, 0xed, 0x67, 0x49, 0x3a, 0x7a, 0xfc, 0x88, 0x2e,
	0xa0, 0xff, 0x52, 0x18, 0xdb, 0x80, 0xf8, 0xef, 0x6e, 0xed, 0xbb, 0x4d, 0x2e, 0xba, 0xfc, 0xf7,
	0xe4, 0xd5, 0xb1, 0xfb, 0x34, 0xd7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0xdb, 0xc9, 0xe5,
	0x47, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommunicationClient is the client API for Communication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationClient interface {
	AcquireTargets(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*EventMessage, error)
	ListTargets(ctx context.Context, in *TargetRequestMessage, opts ...grpc.CallOption) (*TargetResponseMessage, error)
}

type communicationClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicationClient(cc grpc.ClientConnInterface) CommunicationClient {
	return &communicationClient{cc}
}

func (c *communicationClient) AcquireTargets(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*EventMessage, error) {
	out := new(EventMessage)
	err := c.cc.Invoke(ctx, "/destroyer_pb.Communication/acquireTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) ListTargets(ctx context.Context, in *TargetRequestMessage, opts ...grpc.CallOption) (*TargetResponseMessage, error) {
	out := new(TargetResponseMessage)
	err := c.cc.Invoke(ctx, "/destroyer_pb.Communication/listTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationServer is the server API for Communication service.
type CommunicationServer interface {
	AcquireTargets(context.Context, *EventMessage) (*EventMessage, error)
	ListTargets(context.Context, *TargetRequestMessage) (*TargetResponseMessage, error)
}

// UnimplementedCommunicationServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicationServer struct {
}

func (*UnimplementedCommunicationServer) AcquireTargets(ctx context.Context, req *EventMessage) (*EventMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireTargets not implemented")
}
func (*UnimplementedCommunicationServer) ListTargets(ctx context.Context, req *TargetRequestMessage) (*TargetResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTargets not implemented")
}

func RegisterCommunicationServer(s *grpc.Server, srv CommunicationServer) {
	s.RegisterService(&_Communication_serviceDesc, srv)
}

func _Communication_AcquireTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).AcquireTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/destroyer_pb.Communication/AcquireTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).AcquireTargets(ctx, req.(*EventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_ListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).ListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/destroyer_pb.Communication/ListTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).ListTargets(ctx, req.(*TargetRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Communication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "destroyer_pb.Communication",
	HandlerType: (*CommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "acquireTargets",
			Handler:    _Communication_AcquireTargets_Handler,
		},
		{
			MethodName: "listTargets",
			Handler:    _Communication_ListTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "destroyer.proto",
}
