version: "3.5"
services:
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    networks:
      - consul-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysql21
    volumes: 
      - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # command: ./docker-entrypoint-initdb.d/init-user-db.sh
  consul:
    image: bitnami/consul:latest
    networks:
      - consul-network
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
  pulsar-standalone:
    image: apachepulsar/pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    expose:
      - 8080
      - 6650
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    networks:
      - consul-network
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
  destroyer:
    container_name: destroyer
    restart: always
    build:
      dockerfile: Dockerfile
      context: destroyer
    environment: 
      - HOST=postgres_db
    depends_on:
      - postgres_db
    networks:
      - consul-network
    image: "destroyer:alpine"
  deathstar:
    container_name: deathstar
    restart: always
    build:
      dockerfile: Dockerfile
      context: deathstar
    depends_on:
      - postgres_db
    networks:
      - consul-network
    image: "deathstar:alpine"
networks:
  consul-network:
    driver: bridge
# Names our volume
volumes:
  my-db:
