version: "3.5"
services:
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    networks:
      - consul-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysql21
    volumes: 
      - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # command: ./docker-entrypoint-initdb.d/init-user-db.sh
  consul:
    image: bitnami/consul:latest
    networks:
      - consul-network
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
  pulsar-standalone:
    image: apachepulsar/pulsar:2.4.0
    container_name: broker
    ports:
      - '6650:6650'
      - '8080:8080'
    volumes:
      - $PWD/data/pulsar:/pulsar/data
    command:
      bin/pulsar standalone
  destroyer:
    container_name: destroyer
    restart: always
    build:
      dockerfile: Dockerfile
      context: destroyer
    environment: 
      - HOST=postgres_db
      - PULSAR=pulsar-standalone
    depends_on:
      - pulsar-standalone
      - postgres_db
    networks:
      - consul-network
    image: "destroyer:alpine"
  deathstar:
    container_name: deathstar
    restart: always
    build:
      dockerfile: Dockerfile
      context: deathstar
    depends_on:
      - pulsar-standalone
      - postgres_db
    networks:
      - consul-network
    image: "deathstar:alpine"
networks:
  consul-network:
    driver: bridge
# Names our volume
volumes:
  my-db:
