// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deathstar.proto

package deathstar_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventRequestMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequestMessage) Reset()         { *m = EventRequestMessage{} }
func (m *EventRequestMessage) String() string { return proto.CompactTextString(m) }
func (*EventRequestMessage) ProtoMessage()    {}
func (*EventRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f9e78c4f4ad07be, []int{0}
}

func (m *EventRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequestMessage.Unmarshal(m, b)
}
func (m *EventRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequestMessage.Marshal(b, m, deterministic)
}
func (m *EventRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequestMessage.Merge(m, src)
}
func (m *EventRequestMessage) XXX_Size() int {
	return xxx_messageInfo_EventRequestMessage.Size(m)
}
func (m *EventRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequestMessage proto.InternalMessageInfo

type EventResponseMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	CreatedOn            string   `protobuf:"bytes,3,opt,name=CreatedOn,proto3" json:"CreatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponseMessage) Reset()         { *m = EventResponseMessage{} }
func (m *EventResponseMessage) String() string { return proto.CompactTextString(m) }
func (*EventResponseMessage) ProtoMessage()    {}
func (*EventResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f9e78c4f4ad07be, []int{1}
}

func (m *EventResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponseMessage.Unmarshal(m, b)
}
func (m *EventResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponseMessage.Marshal(b, m, deterministic)
}
func (m *EventResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponseMessage.Merge(m, src)
}
func (m *EventResponseMessage) XXX_Size() int {
	return xxx_messageInfo_EventResponseMessage.Size(m)
}
func (m *EventResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponseMessage proto.InternalMessageInfo

func (m *EventResponseMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventResponseMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EventResponseMessage) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

type EventMessage struct {
	Id                   string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Data                 []*TargetResponse `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	CreatedOn            string            `protobuf:"bytes,4,opt,name=CreatedOn,proto3" json:"CreatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EventMessage) Reset()         { *m = EventMessage{} }
func (m *EventMessage) String() string { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()    {}
func (*EventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f9e78c4f4ad07be, []int{2}
}

func (m *EventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMessage.Unmarshal(m, b)
}
func (m *EventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMessage.Marshal(b, m, deterministic)
}
func (m *EventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMessage.Merge(m, src)
}
func (m *EventMessage) XXX_Size() int {
	return xxx_messageInfo_EventMessage.Size(m)
}
func (m *EventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMessage proto.InternalMessageInfo

func (m *EventMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventMessage) GetData() []*TargetResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EventMessage) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

type TargetResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	CreatedOn            string   `protobuf:"bytes,3,opt,name=CreatedOn,proto3" json:"CreatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetResponse) Reset()         { *m = TargetResponse{} }
func (m *TargetResponse) String() string { return proto.CompactTextString(m) }
func (*TargetResponse) ProtoMessage()    {}
func (*TargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f9e78c4f4ad07be, []int{3}
}

func (m *TargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetResponse.Unmarshal(m, b)
}
func (m *TargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetResponse.Marshal(b, m, deterministic)
}
func (m *TargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetResponse.Merge(m, src)
}
func (m *TargetResponse) XXX_Size() int {
	return xxx_messageInfo_TargetResponse.Size(m)
}
func (m *TargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TargetResponse proto.InternalMessageInfo

func (m *TargetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TargetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TargetResponse) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func init() {
	proto.RegisterType((*EventRequestMessage)(nil), "deathstar_pb.EventRequestMessage")
	proto.RegisterType((*EventResponseMessage)(nil), "deathstar_pb.EventResponseMessage")
	proto.RegisterType((*EventMessage)(nil), "deathstar_pb.EventMessage")
	proto.RegisterType((*TargetResponse)(nil), "deathstar_pb.TargetResponse")
}

func init() {
	proto.RegisterFile("deathstar.proto", fileDescriptor_0f9e78c4f4ad07be)
}

var fileDescriptor_0f9e78c4f4ad07be = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x49, 0x4d, 0x2c,
	0xc9, 0x28, 0x2e, 0x49, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x81, 0x0b, 0xc4,
	0x17, 0x24, 0x29, 0x89, 0x72, 0x09, 0xbb, 0x96, 0xa5, 0xe6, 0x95, 0x04, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0xf8, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x2a, 0xc5, 0x71, 0x89, 0x40, 0x85, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xa1, 0xe2, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x9e, 0x29, 0x42, 0x12, 0x5c, 0xec, 0x50, 0x29, 0x09, 0x26, 0xb0,
	0x20, 0x8c, 0x2b, 0x24, 0xc3, 0xc5, 0xe9, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0x9a, 0xe2, 0x9f, 0x27,
	0xc1, 0x0c, 0x96, 0x43, 0x08, 0x28, 0x35, 0x31, 0x72, 0xf1, 0x80, 0x2d, 0xc0, 0x65, 0xb0, 0x10,
	0x17, 0x8b, 0x5f, 0x62, 0x2e, 0xcc, 0x54, 0x30, 0x5b, 0xc8, 0x80, 0x8b, 0xc5, 0x25, 0xb1, 0x24,
	0x51, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x46, 0x0f, 0xd9, 0x23, 0x7a, 0x21, 0x89, 0x45,
	0xe9, 0xa9, 0x70, 0xf7, 0x06, 0x81, 0x55, 0xa2, 0x3a, 0x82, 0x05, 0xdd, 0x11, 0x11, 0x5c, 0x7c,
	0xa8, 0xba, 0xa8, 0xe5, 0x3d, 0xa3, 0x74, 0x2e, 0x5e, 0xe7, 0xfc, 0xdc, 0xdc, 0xd2, 0xbc, 0xcc,
	0xe4, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0xa1, 0x30, 0x2e, 0xee, 0xe2, 0x92, 0xfc, 0xa2, 0x54, 0x88,
	0x7d, 0x42, 0x8a, 0xa8, 0x6e, 0xc7, 0x12, 0x03, 0x52, 0x4a, 0x58, 0x95, 0xa0, 0xc4, 0x86, 0x12,
	0x43, 0x12, 0x1b, 0x38, 0x4e, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xea, 0x9d, 0x06, 0x6b,
	0xe6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommunicationClient is the client API for Communication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationClient interface {
	StoreTarget(ctx context.Context, in *EventRequestMessage, opts ...grpc.CallOption) (*EventResponseMessage, error)
}

type communicationClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicationClient(cc grpc.ClientConnInterface) CommunicationClient {
	return &communicationClient{cc}
}

func (c *communicationClient) StoreTarget(ctx context.Context, in *EventRequestMessage, opts ...grpc.CallOption) (*EventResponseMessage, error) {
	out := new(EventResponseMessage)
	err := c.cc.Invoke(ctx, "/deathstar_pb.Communication/storeTarget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationServer is the server API for Communication service.
type CommunicationServer interface {
	StoreTarget(context.Context, *EventRequestMessage) (*EventResponseMessage, error)
}

// UnimplementedCommunicationServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicationServer struct {
}

func (*UnimplementedCommunicationServer) StoreTarget(ctx context.Context, req *EventRequestMessage) (*EventResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreTarget not implemented")
}

func RegisterCommunicationServer(s *grpc.Server, srv CommunicationServer) {
	s.RegisterService(&_Communication_serviceDesc, srv)
}

func _Communication_StoreTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).StoreTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deathstar_pb.Communication/StoreTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).StoreTarget(ctx, req.(*EventRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Communication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deathstar_pb.Communication",
	HandlerType: (*CommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "storeTarget",
			Handler:    _Communication_StoreTarget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deathstar.proto",
}
